### 특정 상품 하나에 대한 정보 가져오는 요청
GET http://localhost:7010/api/products/1

### 특정 상품 하나에 대한 정보 가져오는 요청 (상품 존재하지 않을 경우)
GET http://localhost:7010/api/products/111

### 해당하는 페이지 내의 상품 리스트를 가져오는 요청
GET http://localhost:7010/api/products?page=0&size=3

### 페이지와 사이즈를 지정해 주지 않은 경우 (default 값인 page=0, size=5)
GET http://localhost:7010/api/products


### 상품 생성하는 요청
POST http://localhost:7010/api/products
Content-Type: application/json

{
  "name": "상품명",
  "description": "상품설명"
}

### 상품 생성하는 요청 (정확한 요청이 아닌 경우)
POST http://localhost:7010/api/products
Content-Type: application/json

{
  "description": "상품설명"
}

### 상품에 대한 정보를 수정하는 요청
PUT http://localhost:7010/api/products
Content-Type: application/json

{
  "id": 1,
  "name": "새로운이름",
  "description": "새로운상품"
}

### 상품에 대한 정보를 수정하는 요청 (상품이 존재하지 않는 경우)
PUT http://localhost:7010/api/products
Content-Type: application/json

{
  "id": 111,
  "name": "새로운이름",
  "description": "새로운상품"
}

### 상품에 대한 정보를 수정하는 요청 (요청이 정확하지 않은 경우)
PUT http://localhost:7010/api/products
Content-Type: application/json

{
  "name": "새로운이름",
  "description": "새로운상품"
}

### 상품을 삭제하는 요청
DELETE http://localhost:7010/api/products/2

### 상품을 삭제하는 요청 (상품이 존재하지 않는 경우)
DELETE http://localhost:7010/api/products/111
